import createClient from "openapi-fetch";
// `schema.d.ts` is generated by `pnpm api:generate` from the backend OpenAPI contract.
import type { paths } from "./schema";

/** Browser client. Goes through the same-origin `/backend` proxy (see next.config.ts) so cookies are first-party. */
export const apiClient = createClient<paths>({ baseUrl: "/backend" });
