import createClient from "openapi-fetch";
// `schema.d.ts` is generated by `pnpm api:generate` from the backend OpenAPI contract.
import type { paths } from "./schema";

export const apiClient = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:4000",
});
