/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IngredientsController_search"];
        put?: never;
        post: operations["IngredientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TagsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecipesController_list"];
        put?: never;
        post: operations["RecipesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecipesController_get"];
        put: operations["RecipesController_update"];
        post?: never;
        delete: operations["RecipesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthChecksDto: {
            /** @enum {string} */
            postgres: "up" | "down";
            /** @enum {string} */
            redis: "up" | "down";
        };
        HealthResponseDto: {
            /** @enum {string} */
            status: "ok" | "error";
            checks: components["schemas"]["HealthChecksDto"];
        };
        Ingredient: {
            /** Format: uuid */
            id: string;
            name: string;
            aliases: string[];
            /** @enum {string} */
            aisle: "produce" | "meat" | "seafood" | "dairy" | "pantry" | "spices" | "frozen" | "other";
            /** @enum {string} */
            defaultUnit: "g" | "ml" | "piece";
            densityGPerMl: number | null;
            isFermented: boolean;
        };
        SearchIngredientsQuery: {
            q?: string;
            /** @default 20 */
            limit: number;
        };
        CreateIngredient: {
            name: string;
            /** @default [] */
            aliases: string[];
            /**
             * @default other
             * @enum {string}
             */
            aisle: "produce" | "meat" | "seafood" | "dairy" | "pantry" | "spices" | "frozen" | "other";
            /**
             * @default g
             * @enum {string}
             */
            defaultUnit: "g" | "ml" | "piece";
            /** @default null */
            densityGPerMl: number | null;
        };
        TagDimension: {
            id: number;
            slug: string;
            label: string;
            tags: {
                id: number;
                slug: string;
                label: string;
            }[];
        };
        RecipeInput: {
            title: string;
            description?: string | null;
            /** Format: uri */
            imageUrl?: string | null;
            /** Format: uri */
            sourceUrl?: string | null;
            /** @default 2 */
            baseServings: number;
            totalMinutes: number;
            difficulty: number;
            steps: {
                text: string;
                timerSeconds?: number;
                timerLabel?: string;
            }[];
            /** @default [] */
            ingredients: {
                /** Format: uuid */
                ingredientId: string;
                quantity: number | string;
                unit?: string | null;
                note?: string | null;
            }[];
            /** @default [] */
            tagIds: number[];
        };
        ListRecipesQuery: {
            tags?: string;
            rarity?: string;
            maxMinutes?: number;
            q?: string;
            cursor?: string;
            /** @default 20 */
            limit: number;
        };
        RecipeDetail: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            imageUrl: string | null;
            baseServings: number;
            totalMinutes: number;
            difficulty: number;
            /** @enum {string} */
            rarity: "white" | "blue" | "purple" | "pink" | "red";
            tags: {
                id: number;
                slug: string;
                label: string;
                dimension: string;
            }[];
            /** Format: date-time */
            createdAt: string;
            sourceUrl: string | null;
            /** Format: date-time */
            updatedAt: string;
            steps: {
                order: number;
                text: string;
                timerSeconds?: number;
                timerLabel?: string;
            }[];
            ingredients: {
                ingredient: {
                    /** Format: uuid */
                    id: string;
                    name: string;
                    /** @enum {string} */
                    aisle: "produce" | "meat" | "seafood" | "dairy" | "pantry" | "spices" | "frozen" | "other";
                };
                quantity: number;
                /** @enum {string} */
                unit: "g" | "ml" | "piece";
                note: string | null;
            }[];
        };
        RecipeList: {
            items: {
                /** Format: uuid */
                id: string;
                title: string;
                description: string | null;
                imageUrl: string | null;
                baseServings: number;
                totalMinutes: number;
                difficulty: number;
                /** @enum {string} */
                rarity: "white" | "blue" | "purple" | "pink" | "red";
                tags: {
                    id: number;
                    slug: string;
                    label: string;
                    dimension: string;
                }[];
                /** Format: date-time */
                createdAt: string;
            }[];
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    IngredientsController_search: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"][];
                };
            };
        };
    };
    IngredientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngredient"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    TagsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDimension"][];
                };
            };
        };
    };
    RecipesController_list: {
        parameters: {
            query?: {
                tags?: string;
                rarity?: string;
                maxMinutes?: number;
                q?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeList"];
                };
            };
        };
    };
    RecipesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
        };
    };
    RecipesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
        };
    };
    RecipesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
        };
    };
    RecipesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
