import type { SeedIngredient } from './seed-ingredient.type.js';

// Produce, herbs, eggs and fresh protein. Tuple: name, aliases, aisle, defaultUnit, density?, fermented?
export const SEED_FRESH_INGREDIENTS: SeedIngredient[] = [
  // Vegetables
  ['Hành lá', ['scallion', 'green onion', 'spring onion'], 'produce', 'g'],
  ['Hành tây', ['onion', 'yellow onion'], 'produce', 'g'],
  ['Hành tím', ['shallot'], 'produce', 'piece'],
  ['Tỏi', ['garlic'], 'produce', 'piece'],
  ['Gừng', ['ginger'], 'produce', 'g'],
  ['Riềng', ['galangal'], 'produce', 'g'],
  ['Nghệ tươi', ['fresh turmeric'], 'produce', 'g'],
  ['Sả', ['lemongrass'], 'produce', 'piece'],
  ['Ớt', ['chili', 'chilli', 'red chili'], 'produce', 'piece'],
  ['Ớt chuông', ['bell pepper', 'capsicum'], 'produce', 'g'],
  ['Cà chua', ['tomato'], 'produce', 'g'],
  ['Cà rốt', ['carrot'], 'produce', 'g'],
  ['Khoai tây', ['potato'], 'produce', 'g'],
  ['Khoai lang', ['sweet potato'], 'produce', 'g'],
  ['Củ cải trắng', ['daikon', 'white radish'], 'produce', 'g'],
  ['Su hào', ['kohlrabi'], 'produce', 'g'],
  ['Bắp cải', ['cabbage'], 'produce', 'g'],
  ['Súp lơ xanh', ['broccoli'], 'produce', 'g'],
  ['Súp lơ trắng', ['cauliflower'], 'produce', 'g'],
  ['Cải thìa', ['bok choy', 'pak choi'], 'produce', 'g'],
  ['Cải ngọt', ['choy sum'], 'produce', 'g'],
  ['Cải xanh', ['mustard greens'], 'produce', 'g'],
  ['Cải thảo', ['napa cabbage', 'chinese cabbage'], 'produce', 'g'],
  ['Rau muống', ['water spinach', 'morning glory'], 'produce', 'g'],
  ['Rau bina', ['spinach'], 'produce', 'g'],
  ['Xà lách', ['lettuce'], 'produce', 'g'],
  ['Dưa chuột', ['cucumber', 'dưa leo'], 'produce', 'g'],
  ['Bí đỏ', ['pumpkin', 'kabocha'], 'produce', 'g'],
  ['Bí xanh', ['winter melon', 'bí đao'], 'produce', 'g'],
  ['Bí ngòi', ['zucchini', 'courgette'], 'produce', 'g'],
  ['Mướp', ['loofah', 'luffa'], 'produce', 'g'],
  ['Mướp đắng', ['bitter melon', 'khổ qua'], 'produce', 'g'],
  ['Cà tím', ['eggplant', 'aubergine'], 'produce', 'g'],
  ['Đậu bắp', ['okra'], 'produce', 'g'],
  ['Đậu cove', ['green beans', 'french beans'], 'produce', 'g'],
  ['Đậu Hà Lan', ['green peas', 'snow peas'], 'produce', 'g'],
  ['Ngô', ['corn', 'bắp'], 'produce', 'g'],
  ['Măng tre', ['bamboo shoots'], 'produce', 'g'],
  ['Giá đỗ', ['bean sprouts'], 'produce', 'g'],
  ['Măng tây', ['asparagus'], 'produce', 'g'],
  ['Cần tây', ['celery'], 'produce', 'g'],
  ['Củ sen', ['lotus root'], 'produce', 'g'],
  ['Khoai môn', ['taro'], 'produce', 'g'],
  ['Sắn', ['cassava', 'khoai mì'], 'produce', 'g'],
  // Mushrooms
  ['Nấm hương', ['shiitake', 'shiitake mushroom'], 'produce', 'g'],
  ['Nấm rơm', ['straw mushroom'], 'produce', 'g'],
  ['Nấm kim châm', ['enoki'], 'produce', 'g'],
  ['Nấm mỡ', ['button mushroom', 'champignon'], 'produce', 'g'],
  ['Nấm bào ngư', ['oyster mushroom'], 'produce', 'g'],
  ['Mộc nhĩ', ['wood ear mushroom'], 'produce', 'g'],
  // Herbs
  ['Rau mùi', ['cilantro', 'coriander', 'ngò rí'], 'produce', 'g'],
  ['Húng quế', ['thai basil', 'basil'], 'produce', 'g'],
  ['Rau thơm', ['mixed herbs'], 'produce', 'g'],
  ['Thì là', ['dill'], 'produce', 'g'],
  ['Tía tô', ['perilla', 'shiso'], 'produce', 'g'],
  ['Lá chanh', ['kaffir lime leaf', 'makrut lime leaf'], 'produce', 'g'],
  ['Lá nguyệt quế', ['bay leaf'], 'produce', 'piece'],
  ['Bạc hà', ['mint'], 'produce', 'g'],
  ['Ngò gai', ['culantro', 'sawtooth coriander'], 'produce', 'g'],
  ['Rau răm', ['vietnamese coriander'], 'produce', 'g'],
  ['Rau mùi tây', ['parsley'], 'produce', 'g'],
  ['Lá lốt', ['betel leaf', 'la lot'], 'produce', 'g'],
  // Fruit
  ['Chanh', ['lime', 'lemon'], 'produce', 'piece'],
  ['Chanh vàng', ['yellow lemon'], 'produce', 'piece'],
  ['Cam', ['orange'], 'produce', 'piece'],
  ['Dứa', ['pineapple', 'thơm', 'khóm'], 'produce', 'g'],
  ['Chuối', ['banana'], 'produce', 'piece'],
  ['Xoài', ['mango'], 'produce', 'g'],
  ['Táo', ['apple'], 'produce', 'piece'],
  ['Bơ', ['avocado'], 'produce', 'piece'],
  ['Me', ['tamarind'], 'produce', 'g'],
  ['Dừa tươi', ['fresh coconut'], 'produce', 'piece'],
  // Eggs and tofu
  ['Trứng gà', ['egg', 'chicken egg'], 'dairy', 'piece'],
  ['Trứng vịt', ['duck egg'], 'dairy', 'piece'],
  ['Trứng cút', ['quail egg'], 'dairy', 'piece'],
  ['Đậu phụ', ['tofu', 'đậu hũ'], 'produce', 'g'],
  ['Đậu phụ chiên', ['fried tofu'], 'produce', 'g'],
  // Meat
  ['Thịt ba chỉ', ['pork belly'], 'meat', 'g'],
  ['Thịt lợn xay', ['ground pork', 'minced pork', 'thịt heo xay'], 'meat', 'g'],
  ['Thịt nạc vai', ['pork shoulder'], 'meat', 'g'],
  ['Sườn lợn', ['pork ribs', 'sườn heo'], 'meat', 'g'],
  ['Chân giò', ['pork hock', 'pork knuckle'], 'meat', 'g'],
  ['Thịt bò', ['beef'], 'meat', 'g'],
  ['Thịt bò xay', ['ground beef', 'minced beef'], 'meat', 'g'],
  ['Thịt thăn bò', ['beef tenderloin', 'beef sirloin'], 'meat', 'g'],
  ['Bắp bò', ['beef shank'], 'meat', 'g'],
  ['Đuôi bò', ['oxtail'], 'meat', 'g'],
  ['Ức gà', ['chicken breast'], 'meat', 'g'],
  ['Đùi gà', ['chicken thigh', 'chicken drumstick'], 'meat', 'g'],
  ['Cánh gà', ['chicken wings'], 'meat', 'g'],
  ['Gà nguyên con', ['whole chicken'], 'meat', 'g'],
  ['Thịt vịt', ['duck'], 'meat', 'g'],
  ['Thịt dê', ['goat meat', 'mutton'], 'meat', 'g'],
  ['Lạp xưởng', ['chinese sausage'], 'meat', 'g', null, true],
  ['Thịt xông khói', ['bacon'], 'meat', 'g'],
  ['Xúc xích', ['sausage'], 'meat', 'g'],
  ['Giò lụa', ['vietnamese pork roll', 'chả lụa'], 'meat', 'g'],
  // Seafood
  ['Tôm', ['shrimp', 'prawn'], 'seafood', 'g'],
  ['Mực', ['squid', 'calamari'], 'seafood', 'g'],
  ['Cá hồi', ['salmon'], 'seafood', 'g'],
  ['Cá thu', ['mackerel'], 'seafood', 'g'],
  ['Cá basa', ['basa', 'pangasius'], 'seafood', 'g'],
  ['Cá lóc', ['snakehead fish'], 'seafood', 'g'],
  ['Cá diêu hồng', ['red tilapia'], 'seafood', 'g'],
  ['Cá ngừ', ['tuna'], 'seafood', 'g'],
  ['Cá trích', ['herring', 'sardine'], 'seafood', 'g'],
  ['Cua', ['crab'], 'seafood', 'g'],
  ['Ngao', ['clam', 'nghêu'], 'seafood', 'g'],
  ['Hàu', ['oyster'], 'seafood', 'piece'],
  ['Ốc', ['snail'], 'seafood', 'g'],
  ['Chả cá', ['fish cake'], 'seafood', 'g'],
  ['Tôm khô', ['dried shrimp'], 'seafood', 'g'],
  ['Cá khô', ['dried fish'], 'seafood', 'g'],
];
