import type { SeedIngredient } from './seed-ingredient.type.js';

// Dairy, pantry staples, sauces, spices and frozen goods. Densities are g/ml at room temperature.
export const SEED_PANTRY_INGREDIENTS: SeedIngredient[] = [
  // Dairy
  ['Sữa tươi', ['milk', 'whole milk'], 'dairy', 'ml', 1.03],
  ['Sữa đặc', ['condensed milk'], 'dairy', 'ml', 1.3],
  ['Kem tươi', ['heavy cream', 'whipping cream'], 'dairy', 'ml', 1.0],
  ['Bơ lạt', ['butter', 'unsalted butter'], 'dairy', 'g', 0.96],
  ['Phô mai', ['cheese'], 'dairy', 'g'],
  ['Phô mai mozzarella', ['mozzarella'], 'dairy', 'g'],
  ['Phô mai parmesan', ['parmesan'], 'dairy', 'g'],
  ['Sữa chua', ['yogurt', 'yoghurt'], 'dairy', 'g', 1.03, true],
  ['Sữa dừa', ['coconut milk', 'nước cốt dừa', 'coconut cream'], 'pantry', 'ml', 0.97],
  // Oils and fats
  ['Dầu ăn', ['cooking oil', 'vegetable oil'], 'pantry', 'ml', 0.92],
  ['Dầu ô liu', ['olive oil'], 'pantry', 'ml', 0.91],
  ['Dầu mè', ['sesame oil'], 'pantry', 'ml', 0.92],
  ['Dầu hào', ['oyster sauce'], 'pantry', 'ml', 1.2],
  ['Mỡ lợn', ['lard'], 'pantry', 'g', 0.92],
  // Sauces and condiments
  ['Nước mắm', ['fish sauce'], 'pantry', 'ml', 1.2, true],
  ['Nước tương', ['soy sauce', 'xì dầu'], 'pantry', 'ml', 1.15, true],
  ['Tương ớt', ['chili sauce', 'sriracha'], 'pantry', 'ml', 1.1],
  ['Tương cà', ['ketchup', 'tomato ketchup'], 'pantry', 'ml', 1.15],
  ['Tương bần', ['fermented bean sauce'], 'pantry', 'ml', 1.2, true],
  ['Tương đậu nành', ['soybean paste', 'doenjang'], 'pantry', 'g', 1.1, true],
  ['Tương miso', ['miso', 'miso paste'], 'pantry', 'g', 1.1, true],
  ['Gochujang', ['korean chili paste'], 'pantry', 'g', 1.2, true],
  ['Mắm tôm', ['shrimp paste'], 'pantry', 'g', 1.1, true],
  ['Mắm ruốc', ['fermented shrimp sauce', 'belacan'], 'pantry', 'g', 1.1, true],
  ['Mayonnaise', ['mayo'], 'pantry', 'ml', 0.95],
  ['Mù tạt', ['mustard'], 'pantry', 'ml', 1.05],
  ['Sốt cà chua', ['tomato sauce', 'passata'], 'pantry', 'ml', 1.05],
  ['Cà chua cô đặc', ['tomato paste'], 'pantry', 'g', 1.1],
  ['Sốt teriyaki', ['teriyaki sauce'], 'pantry', 'ml', 1.15],
  ['Mirin', ['rice wine for cooking'], 'pantry', 'ml', 1.05, true],
  ['Rượu nấu ăn', ['cooking wine', 'shaoxing wine', 'sake'], 'pantry', 'ml', 0.98, true],
  ['Giấm', ['vinegar', 'white vinegar'], 'pantry', 'ml', 1.01, true],
  ['Giấm gạo', ['rice vinegar'], 'pantry', 'ml', 1.01, true],
  ['Giấm táo', ['apple cider vinegar'], 'pantry', 'ml', 1.01, true],
  ['Kim chi', ['kimchi'], 'pantry', 'g', 1.0, true],
  ['Dưa muối', ['pickled mustard greens', 'dưa chua'], 'pantry', 'g', 1.0, true],
  ['Cà muối', ['pickled eggplant'], 'pantry', 'g', 1.0, true],
  ['Dưa cải chua', ['pickled cabbage'], 'pantry', 'g', 1.0, true],
  ['Nước dùng gà', ['chicken stock', 'chicken broth'], 'pantry', 'ml', 1.0],
  ['Nước dùng bò', ['beef stock', 'beef broth'], 'pantry', 'ml', 1.0],
  ['Nước', ['water'], 'other', 'ml', 1.0],
  // Sweeteners
  ['Đường', ['sugar', 'white sugar'], 'pantry', 'g', 0.85],
  ['Đường nâu', ['brown sugar'], 'pantry', 'g', 0.93],
  ['Đường phèn', ['rock sugar'], 'pantry', 'g', 0.95],
  ['Mật ong', ['honey'], 'pantry', 'ml', 1.42],
  ['Siro', ['syrup', 'maple syrup'], 'pantry', 'ml', 1.3],
  ['Đường thốt nốt', ['palm sugar'], 'pantry', 'g', 0.95],
  // Flours, starches, grains
  ['Bột mì', ['all-purpose flour', 'wheat flour', 'plain flour'], 'pantry', 'g', 0.53],
  ['Bột mì số 11', ['bread flour', 'high-gluten flour'], 'pantry', 'g', 0.55],
  ['Bột bắp', ['cornstarch', 'corn flour'], 'pantry', 'g', 0.54],
  ['Bột năng', ['tapioca starch', 'tapioca flour'], 'pantry', 'g', 0.6],
  ['Bột gạo', ['rice flour'], 'pantry', 'g', 0.55],
  ['Bột nở', ['baking powder'], 'pantry', 'g', 0.9],
  ['Baking soda', ['bicarbonate of soda', 'bột nổi'], 'pantry', 'g', 1.0],
  ['Men nở', ['yeast', 'dry yeast'], 'pantry', 'g', 0.7],
  ['Bột chiên giòn', ['tempura flour', 'crispy fry mix'], 'pantry', 'g', 0.55],
  ['Vụn bánh mì', ['breadcrumbs', 'panko'], 'pantry', 'g', 0.35],
  ['Gạo tẻ', ['rice', 'white rice', 'jasmine rice'], 'pantry', 'g', 0.85],
  ['Gạo nếp', ['glutinous rice', 'sticky rice'], 'pantry', 'g', 0.85],
  ['Gạo lứt', ['brown rice'], 'pantry', 'g', 0.85],
  ['Yến mạch', ['oats', 'rolled oats'], 'pantry', 'g', 0.4],
  ['Bún', ['rice vermicelli', 'bún tươi'], 'pantry', 'g'],
  ['Phở', ['rice noodles', 'bánh phở'], 'pantry', 'g'],
  ['Mì trứng', ['egg noodles'], 'pantry', 'g'],
  ['Mì ý', ['spaghetti', 'pasta'], 'pantry', 'g'],
  ['Mì udon', ['udon', 'udon noodles'], 'pantry', 'g'],
  ['Miến', ['glass noodles', 'cellophane noodles'], 'pantry', 'g'],
  ['Bánh tráng', ['rice paper'], 'pantry', 'piece'],
  ['Bánh mì', ['bread', 'baguette'], 'pantry', 'piece'],
  // Beans, nuts, dried goods
  ['Đậu xanh', ['mung beans'], 'pantry', 'g', 0.8],
  ['Đậu đen', ['black beans'], 'pantry', 'g', 0.8],
  ['Đậu đỏ', ['red beans', 'adzuki beans'], 'pantry', 'g', 0.8],
  ['Đậu phộng', ['peanuts', 'lạc'], 'pantry', 'g', 0.6],
  ['Vừng', ['sesame seeds', 'mè'], 'pantry', 'g', 0.6],
  ['Hạt điều', ['cashews'], 'pantry', 'g', 0.55],
  ['Hạnh nhân', ['almonds'], 'pantry', 'g', 0.6],
  ['Nấm hương khô', ['dried shiitake'], 'pantry', 'g'],
  ['Rong biển khô', ['nori', 'dried seaweed'], 'pantry', 'piece'],
  ['Rong biển kombu', ['kombu'], 'pantry', 'g'],
  ['Cá bào katsuobushi', ['bonito flakes', 'katsuobushi'], 'pantry', 'g', null, true],
  ['Hành phi', ['fried shallots'], 'pantry', 'g'],
  ['Dừa nạo', ['shredded coconut', 'desiccated coconut'], 'pantry', 'g', 0.35],
  // Spices
  ['Muối', ['salt', 'table salt'], 'spices', 'g', 1.2],
  ['Tiêu đen', ['black pepper', 'hạt tiêu'], 'spices', 'g', 0.5],
  ['Tiêu xay', ['ground pepper', 'ground black pepper'], 'spices', 'g', 0.5],
  ['Bột ngọt', ['msg', 'monosodium glutamate', 'mì chính'], 'spices', 'g', 1.0],
  ['Hạt nêm', ['seasoning powder', 'chicken bouillon'], 'spices', 'g', 0.9],
  ['Bột cà ri', ['curry powder'], 'spices', 'g', 0.5],
  ['Bột nghệ', ['turmeric powder', 'turmeric'], 'spices', 'g', 0.55],
  ['Ớt bột', ['chili powder', 'chili flakes', 'paprika'], 'spices', 'g', 0.45],
  ['Gochugaru', ['korean chili flakes'], 'spices', 'g', 0.4],
  ['Quế', ['cinnamon'], 'spices', 'g', 0.55],
  ['Hoa hồi', ['star anise'], 'spices', 'piece'],
  ['Đinh hương', ['cloves'], 'spices', 'g', 0.5],
  ['Thảo quả', ['black cardamom'], 'spices', 'piece'],
  ['Hạt mùi', ['coriander seeds'], 'spices', 'g', 0.4],
  ['Thì là Ai Cập', ['cumin', 'cumin seeds'], 'spices', 'g', 0.45],
  ['Bột ngũ vị hương', ['five spice powder'], 'spices', 'g', 0.5],
  ['Bột tỏi', ['garlic powder'], 'spices', 'g', 0.55],
  ['Oregano', ['dried oregano'], 'spices', 'g', 0.2],
  ['Húng tây', ['thyme', 'dried thyme'], 'spices', 'g', 0.25],
  ['Rau mùi tây khô', ['dried parsley'], 'spices', 'g', 0.15],
  ['Hạt điều màu', ['annatto seeds', 'bột điều'], 'spices', 'g', 0.5],
  ['Wasabi', ['wasabi paste'], 'spices', 'g', 1.1],
  // Frozen and other
  ['Đậu Hà Lan đông lạnh', ['frozen peas'], 'frozen', 'g'],
  ['Tôm đông lạnh', ['frozen shrimp'], 'frozen', 'g'],
  ['Khoai tây chiên đông lạnh', ['frozen fries', 'frozen french fries'], 'frozen', 'g'],
  ['Há cảo đông lạnh', ['frozen dumplings'], 'frozen', 'piece'],
  ['Rau củ đông lạnh', ['frozen mixed vegetables'], 'frozen', 'g'],
  ['Đá', ['ice', 'ice cubes'], 'frozen', 'g', 0.92],
  ['Lá dứa', ['pandan leaf'], 'other', 'piece'],
  ['Gelatin', ['gelatin powder'], 'pantry', 'g', 0.7],
  ['Ca cao', ['cocoa powder'], 'pantry', 'g', 0.45],
  ['Sô cô la', ['chocolate'], 'pantry', 'g'],
  ['Vani', ['vanilla extract', 'vanilla'], 'pantry', 'ml', 0.95],
  ['Trà', ['tea', 'tea leaves'], 'other', 'g'],
  ['Cà phê', ['coffee', 'ground coffee'], 'other', 'g', 0.4],
];
